### ISSUE TITLE
Adding your own git importation procedure

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/cheminfo-server-setup#11]
pm2 is running as nodejs, it is important to switch the user !

```
su -l nodejs
pm2 stop roc-import
cd /usr/local/rest-on-couch
git clone XXXXXXX
pm2 restart all
```

For private github repository you can use something like:
git clone "https://username:password@github.com/cheminfo/private.git"

**Comment by targos** [comment]
You also want to restart the server, otherwise data will not be available from the web: `pm2 restart roc-server`
