### ISSUE TITLE
Node versions

### ISSUE THREAD

**Issue by maasencioh** [cheminfo/cheminfo-server-setup#14]
When Node it's not installed the script ask to install it from the latest version, but later it checks that it's working on the 5.X version

**Comment by targos** [comment]
We stopped to maintain the script a while ago. The only source of truth is the doc directory now: https://github.com/cheminfo/cheminfo-server-setup/tree/master/doc

**Comment by maasencioh** [comment]
there's any known issue with the 6.x node version? or it's safe to work with it? thanks :+1:

**Comment by targos** [comment]
no, we are running v6.x in production on many servers

**Comment by maasencioh** [comment]
thanks!
