### ISSUE TITLE
build not working ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/cheminfo-server-setup#16]
Could you check the normal build as well as

(cd /usr/local/www/sites/nmr.cheminfo.org/flavor-builder/; node index.js)

that yields to an error and is currently desactivated

**Comment by stropitek** [comment]
Is anybody using the nmr build? It uses an old view database that no longer exists and an old version of the builder. If yes I can migrate it. Otherwise I will delete it.

**Comment by lpatiny** [comment]
Well I guess not ... because indeed on www.nmrdb.org we have the last version. So you should delete it (and also in the crontab) to avoid confusion.
How http://www.nmrdb.org is build then ?

**Comment by stropitek** [comment]
nmrdb.org is not built: it's just a clone of [this repo](https://github.com/cheminfo/nmrdb)

**Comment by stropitek** [comment]
Just to be sure: we don't need nmr.cheminfo.org ?
That's where those views were built

**Comment by stropitek** [comment]
Well it does not even work so if someone was using it we would know
